language: c
# sudo: true
# compiler:
  # - clang


env:
  global:
  - PREFIX=/tmp/local
  - INSTALL_TOP=$PREFIX
  # - PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig
  # - LUA_VERSION=lua-5.3.4
  - LUAROCKS_VERSION=luarocks-2.4.4
  # - PATH=$(pwd)/$LUA_VERSION/src:$PATH
  # - PATH=$PREFIX/bin:/home/travis/build/travis-util/lua-building/$LUA_VERSION/install/bin:$PATH
  - PATH=$PREFIX/bin:$PATH


addons:
  apt:
    packages:
    - libfcgi-dev
    - liblua5.1-dev # helping luarocks with lua 5.1
    - liblua5.2-dev # helping luarocks with lua 5.1
    - lua5.1
    - lua5.2
    # - luarocks # This luarocks (Ubuntu 14.04.5 LTS Trusty) installs for lua 5.1 (see find)
    # - lua-sec # for luarocks install (but not required for luasocket)

before_install:
- wget --quiet https://luarocks.org/releases/$LUAROCKS_VERSION.tar.gz
- tar --gzip --extract --file=$LUAROCKS_VERSION.tar.gz
- cd $LUAROCKS_VERSION
- ls --color
- ./configure --help
- ./configure --program-suffix=5.2 # --prefix=$PREFIX --rocks-tree=/usr/local
# - make build && make install
- sudo -H make bootstrap
# --jobs=$JOBS
# - ls --color $PREFIX
# - ls --color $PREFIX/bin
- if [ -d "$PREFIX" ]; then find $PREFIX -name luarocks ; fi
- find /usr/local -name luarocks
- cd ..

- command -v lua
- lua -v
- lua5.2 -v
- lua5.1 -v
- lua -e 'print("Hello World")'
- lua5.2 -e 'print("Hello World")'
- lua5.1 -e 'print("Hello World")'
- command -v luarocks
- luarocks
- cat /etc/luarocks/config.lua || cat /tmp/local/etc/luarocks/config-5.1.lua || cat /usr/local/etc/luarocks/config-5.1.lua || true
- luarocks help path
- luarocks path
- luarocks help install
- apt-cache policy curl # for SSL downloads with luarocks
- apt-cache policy libssl-dev # for luasec
- apt-cache policy luarocks
# - apt-cache policy lua5.3
- apt-cache policy lua5.2
- apt-cache policy lua5.1


install:
- curl https://luarocks.org/luasocket-3.0rc1-2.src.rock  --remote-name --remote-time --remote-header-name --silent
# Modern versions of luarocks can use curl automatically.
# Consider compalling an up to date version of luarocks.
- sudo -H $(command -v luarocks) install luasocket
# - sudo -H $(command -v luarocks) install luasocket-3.0rc1-2.src.rock
# Error: Your user does not have write permissions in /usr/local/lib/luarocks/rocks 
# -- you may want to run as a privileged user or use your local tree with --local.
- if [ -d "$PREFIX" ]; then find $PREFIX -name socket.lua ; fi
- find /usr/local -name socket.lua # This luarocks installs for lua 5.1
- lua5.2 -e 'require "socket"'
#- lua5.1 -e 'require "socket"'
- curl https://luarocks.org/luasec-0.7alpha-2.src.rock  --remote-name --remote-time --remote-header-name --silent
- ls /usr/lib/x86_64-linux-gnu/libssl.*
- sudo -H env OPENSSL_DIR=/usr/lib/x86_64-linux-gnu $(command -v luarocks) build luasec-0.7alpha-2.src.rock OPENSSL_DIR=/usr/lib/x86_64-linux-gnu
- lua5.2 -e 'require "ssl"'
#- lua5.1 -e 'require "ssl"'
# As long as luarocks cannot use SSL connections, one should get the packages using another utility!


- sudo -H $(command -v luarocks) install wsapi
# Error fetching file: Failed downloading http://luarocks.org/repositories/rocks/manifest
# URL redirected to unsupported protocol - install luasec to get HTTPS support.
- find /usr/local -name wsapi.lua # This luarocks installs for lua 5.1
- lua5.2 -e 'require "wsapi"'
# - lua5.1 -e 'require "wsapi"'
- sudo -H $(command -v luarocks) install wsapi-xavante
- lua5.2 -e 'require "wsapi.xavante"'
# - lua5.1 -e 'require "wsapi.xavante"'
- apt-cache policy libfcgi-dev
- apt-cache policy libfcgi0ldbl
- sudo -H $(command -v luarocks) install wsapi-fcgi
- lua5.2 -e 'require "wsapi.fastcgi"'
# - lua5.1 -e 'require "wsapi.fastcgi"'


script:
- true
