language: lua

dist: trusty

addons:
  apt:
    packages:
    - libfcgi-dev
    - liblua5.1-dev # helping luarocks with lua 5.1
    - lua5.1
    - luarocks # This luarocks (Ubuntu 14.04.5 LTS Trusty) installs for lua 5.1 (see find)
    - lua-sec # for luarocks install (but not required for luasocket)

before_install:
- command -v lua
- lua -v
- lua -e 'print("Hello World")'
- command -v luarocks
- luarocks
- cat /etc/luarocks/config.lua
- luarocks help path
- luarocks path
- luarocks help install
- apt-cache policy curl # for SSL downloads with luarocks


install:
# - sudo -H luarocks install luasocket
# Error: Your user does not have write permissions in /usr/local/lib/luarocks/rocks 
# -- you may want to run as a privileged user or use your local tree with --local.
# - find /usr/local -name socket.lua # This luarocks installs for lua 5.1
- lua -e 'require "socket"'
# - sudo -H luarocks install luasec
- lua -e 'require "ssl"'
# As long as luarocks cannot use SSL connections, one should get the packages using another utility!


- sudo -H luarocks install wsapi
# Error fetching file: Failed downloading http://luarocks.org/repositories/rocks/manifest
# URL redirected to unsupported protocol - install luasec to get HTTPS support.
- find /usr/local -name wsapi.lua # This luarocks installs for lua 5.1
- lua -e 'require "wsapi"'
- sudo -H luarocks install wsapi-xavante
- lua -e 'require "wsapi.xavante"'
- apt-cache policy libfcgi-dev
- apt-cache policy libfcgi0ldbl
- sudo -H luarocks install wsapi-fcgi
- lua -e 'require "wsapi.fastcgi"'


script:
- true
